FlightManagerApp/FlightManagerApp/Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlightManagerApp.Models;

namespace FlightManagerApp.Controllers
{
    public class FlightsController : Controller
    {
        private readonly FlightManagerDbContext _context;

        public FlightsController(FlightManagerDbContext context)
        {
            _context = context;
        }

        // GET: Flights
        public async Task<IActionResult> Index()
        {
            if(HttpContext.Session.GetString("IsAuthenticated") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
              return _context.Flights != null ? 
                          View(await _context.Flights.ToListAsync()) :
                          Problem("Entity set 'FlightManagerDbContext.Flights'  is null.");
        }

        // GET: Flights/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.FlightId == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FlightId,DepartureLocation,ArrivalLocation,DepartureDateTime,ArrivalDateTime,PlaneType,PlaneNumber,PilotName,PassengerCapacity,BusinessClassCapacity")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }
        
        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightId,DepartureLocation,ArrivalLocation,DepartureDateTime,ArrivalDateTime,PlaneType,PlaneNumber,PilotName,PassengerCapacity,BusinessClassCapacity")] Flight flight)
        {
            if (id != flight.FlightId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.FlightId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(flight);
        }

        // GET: Flights/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Flights == null)
            {
                return NotFound();
            }

            var flight = await _context.Flights
                .FirstOrDefaultAsync(m => m.FlightId == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Flights == null)
            {
                return Problem("Entity set 'FlightManagerDbContext.Flights'  is null.");
            }
            var flight = await _context.Flights.FindAsync(id);
            if (flight != null)
            {
                _context.Flights.Remove(flight);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FlightExists(int id)
        {
          return (_context.Flights?.Any(e => e.FlightId == id)).GetValueOrDefault();
        }
    }
}

FlightManagerApp/FlightManagerApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FlightManagerApp.Models;

namespace FlightManagerApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly FlightManagerDbContext _context;

        public UsersController(FlightManagerDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true" && HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return _context.Users != null ? 
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'FlightManagerDbContext.Users'  is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true" && HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true" && HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,Password,Email,FirstName,LastName,Egn,Address,PhoneNumber,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true" && HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,Password,Email,FirstName,LastName,Egn,Address,PhoneNumber,Role")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (HttpContext.Session.GetString("IsAuthenticated") != "true" && HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'FlightManagerDbContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

FlightManagerApp/FlightManagerApp/Views/Shared/_FlightReservation.cshtml
    @model FlightManagerApp.Models.Reservation

@{
    ViewData["Title"] = "Create";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
        <form asp-action="PartialCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="input-container" style="display:flex;">
                <div class="left">
                    <div class="form-group">
                        <label asp-for="FirstName" class="control-label"></label>
                        <input asp-for="FirstName" class="form-control" maxlength="50" required />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="MiddleName" class="control-label"></label>
                        <input asp-for="MiddleName" class="form-control" maxlength="50" required />
                        <span asp-validation-for="MiddleName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" maxlength="50" required />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
                <div class="middle">
                    <div class="form-group">
                        <label asp-for="Egn" class="control-label"></label>
                        <input asp-for="Egn" class="form-control" pattern="\d{10}" required />
                        <span asp-validation-for="Egn" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" type="email" required />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control" maxlength="13" required />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                </div>
                <div class="right">
                    <div class="form-group">
                        <label asp-for="Nationality" class="control-label"></label>
                        <input asp-for="Nationality" class="form-control" pattern="[A-Z]{2}" placeholder="XX" maxlength="2" required />
                        <span asp-validation-for="Nationality" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TicketType" class="control-label"></label>
                        <select asp-for="TicketType" class="form-control" required>
                            <option value="">Choose a ticket type</option>
                            <option value="Business">Business</option>
                            <option value="Economics">Economics</option>
                        </select>
                        <span asp-validation-for="TicketType" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FlightId" class="control-label"></label>
                        <select asp-for="FlightId" class="form-control" asp-items="ViewBag.FlightId" required></select>
                    </div>
                </div>
            </div>
            <div class="form-group">
            <input type="submit" value="Book" class="btn btn-primary" onclick="onSubmit()" />
            </div>
    </form>
</body>
</html>

FlightManagerApp/FlightManagerApp/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    var session = HttpContextAccessor.HttpContext?.Session;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightManagerApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlightManagerApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PaperFlight</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
                @if(session != null)
                {
                    @if (session.GetString("IsAuthenticated") == "true")
                    {
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-end">
                            <ul class="navbar-nav d-sm-inline-flex flex-grow-1 justify-content-end">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Flights" asp-action="Index">Flights History</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservations History</a>
                                </li>
                                @if(session.GetString("IsAdmin")=="true")
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users Control Panel</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    }
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div>
            &copy; 2023 - PaperFlight
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FlightManagerApp/FlightManagerApp/Views/Shared/_PassengerChooser.cshtml
@model PassengerChooserModel
@{
    Layout = null;
}

<form asp-action="DisplayPassengerForms" asp-controller="Reservations" method="post">
    <div class="form-flex">
    <div class="form-group">
        <label asp-for="Count">Number of Passengers:</label>
        <input asp-for="Count" class="form-control" />
        <span asp-validation-for="Count" class="text-danger" min="1" max="10" required></span>
    </div>

    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="FlightId">Flight ID:</label>
        <input asp-for="FlightId" class="form-control" readonly="readonly" />
        <span asp-validation-for="FlightId" class="text-danger"></span>
    </div>
    </div>
    <button type="submit" class="purple-button">Book</button>
</form>

<div id="passenger-list">
    <!-- Existing passenger list goes here -->
</div>

<script>
    $(function () {
        $('form').submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('action'),
                type: 'POST',
                data: $(this).serialize(),
                success: function (result) {
                    $('#passenger-list').html(result).fadeIn("slow");
                }
            });
        });
    });
</script>

FlightManagerApp/FlightManagerApp/Views/Shared/_PassengersForm.cshtml
@model List<PassengerModel>


@using (Html.BeginForm("MakeReservation", "Reservations", FormMethod.Post))
{
    <div class="background-wrapper">
    <h2>Add Passengers</h2>
    <div class="passenger-forms">
    @for (int i = 0; i < Model.Count; i++)
    {
        <div class="passenger-form">
        <h4>Passenger @(i + 1)</h4>
        <div class="passenger-box">
            <div>
                @Html.LabelFor(m => m[i].FirstName)
                @Html.LabelFor(m => m[i].LastName)
                @Html.LabelFor(m => m[i].MiddleName)
                @Html.LabelFor(m => m[i].Egn)
                @Html.LabelFor(m => m[i].TelephoneNumber)
                @Html.LabelFor(m => m[i].Nationality)
                @Html.LabelFor(m => m[i].TicketType)
            </div>
            <div>
                @Html.TextBoxFor(m => m[i].FirstName)
                @Html.TextBoxFor(m => m[i].LastName)
                @Html.TextBoxFor(m => m[i].MiddleName)
                @Html.TextBoxFor(m => m[i].Egn)
                @Html.TextBoxFor(m => m[i].TelephoneNumber)
                @Html.TextBoxFor(m => m[i].Nationality)
                @Html.TextBoxFor(m => m[i].TicketType)
                @Html.HiddenFor(m => m[i].FlightId)
                @Html.HiddenFor(m => m[i].Email)
            </div>
            </div>
            </div>
    }

    </div>
    <button type="submit" class="purple-button">Add Passengers</button>
    </div>
}